name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch: #github页面手动触发
  push:
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]

env:
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # https://github.com/docker/login-action
      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # https://github.com/docker/build-push-action
      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./asset/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ needs.get-tags.outputs.tags }}
            ${{ env.IMAGE_NAME }}:latest  
